server:
  port: 8077
  servlet:
    context-path: /ll

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdatabase?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    username: root
    password: mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  ##驼峰匹配
  configuration:
    map-underscore-to-camel-case: true




